import 'package:watering_plants/models/device.dart';

List deviceList = [
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [405, 1340],
        'co2': [812, 2200],
      },
        
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [405, 1340],
        'co2': [812, 2200],
      },    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [405, 1340],
        'co2': [812, 2200],
      }, 
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [405, 1340],
        'co2': [812, 2200],
      },    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [405, 1340],
        'co2': [812, 2200],
      },    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [405, 1340],
        'co2': [812, 2200],
      },    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [0, 100],
        'co2': [812, 2200],
      },    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [0, 100],
        'co2': [812, 2200],
      },    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [0, 100],
        'co2': [812, 2200],
      },    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [0, 100],
        'co2': [812, 2200],
      },    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [0, 100],
        'co2': [812, 2200],
      },    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [0, 100],
        'co2': [812, 2200],
      },    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [405, 1340],
        'co2': [812, 2200],
      },    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 1017.0,
        temperature: 18.7,
        humidity: 77.0,
        tvoc: 879,
        co2: 2078,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
        minMaxValue: {
        'barometricPressure': [142, 1017],
        'temperature': [0, 40],
        'humidity': [0, 100],
        'tvoc': [405, 1340],
        'co2': [812, 2200],
      },    
    ),
  ];