import 'package:watering_plants/models/device.dart';

List deviceList = [
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // salmon
    Device(
        name: "Salmon",
        zone: "Zone A",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
    // tuna
    Device(
        name: "Tuna",
        zone: "Zone B",
        imagePath: "lib/images/home/watering-plants(2).png",
        date: DateTime.now(),
        barometricPressure: 70.0,
        temperature: 37.0,
        humidity: 60.0,
        tvoc: 87,
        co2: 25,
        unite: {'barometricPressure': 'ppm', 'temperature': '°C', 'humidity': '%H', 'tvoc': 'ppm', 'co2': 'ppm'},    
    ),
  ];