// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3v4iH0Ge4y2nKDfPy1enqm2-Mk3EXBGs',
    appId: '1:485449394301:web:4206d1c057444047446914',
    messagingSenderId: '485449394301',
    projectId: 'watering-plants-70f63',
    authDomain: 'watering-plants-70f63.firebaseapp.com',
    storageBucket: 'watering-plants-70f63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvpBKZ7EIS83TeuFOJp1kQmqQ0lOLoM6M',
    appId: '1:485449394301:android:1619a81225df4515446914',
    messagingSenderId: '485449394301',
    projectId: 'watering-plants-70f63',
    storageBucket: 'watering-plants-70f63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5DE2Ga52jWG47n9fGYeGRVfFgyl3GlRo',
    appId: '1:485449394301:ios:fabd238a07b6bca5446914',
    messagingSenderId: '485449394301',
    projectId: 'watering-plants-70f63',
    storageBucket: 'watering-plants-70f63.appspot.com',
    iosBundleId: 'com.example.wateringPlants',
  );
}
